import type { City } from '../types/game';

// Simplified USA map for Power Grid
// Coordinates are in a 1000x600 space for SVG rendering
export const USA_MAP: City[] = [
  // Northwest Region
  {
    id: 'seattle',
    name: 'Seattle',
    region: 'northwest',
    x: 120,
    y: 80,
    connections: [
      { cityId: 'portland', cost: 3 },
      { cityId: 'boise', cost: 8 },
    ],
  },
  {
    id: 'portland',
    name: 'Portland',
    region: 'northwest',
    x: 110,
    y: 130,
    connections: [
      { cityId: 'seattle', cost: 3 },
      { cityId: 'boise', cost: 13 },
      { cityId: 'san-francisco', cost: 14 },
    ],
  },
  {
    id: 'boise',
    name: 'Boise',
    region: 'northwest',
    x: 180,
    y: 140,
    connections: [
      { cityId: 'seattle', cost: 8 },
      { cityId: 'portland', cost: 13 },
      { cityId: 'salt-lake-city', cost: 8 },
    ],
  },

  // Southwest Region
  {
    id: 'san-francisco',
    name: 'San Francisco',
    region: 'southwest',
    x: 100,
    y: 240,
    connections: [
      { cityId: 'portland', cost: 14 },
      { cityId: 'las-vegas', cost: 10 },
      { cityId: 'los-angeles', cost: 10 },
    ],
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    region: 'southwest',
    x: 130,
    y: 300,
    connections: [
      { cityId: 'san-francisco', cost: 10 },
      { cityId: 'las-vegas', cost: 9 },
      { cityId: 'san-diego', cost: 3 },
      { cityId: 'phoenix', cost: 11 },
    ],
  },
  {
    id: 'san-diego',
    name: 'San Diego',
    region: 'southwest',
    x: 140,
    y: 350,
    connections: [
      { cityId: 'los-angeles', cost: 3 },
      { cityId: 'phoenix', cost: 14 },
    ],
  },
  {
    id: 'las-vegas',
    name: 'Las Vegas',
    region: 'southwest',
    x: 180,
    y: 260,
    connections: [
      { cityId: 'san-francisco', cost: 10 },
      { cityId: 'los-angeles', cost: 9 },
      { cityId: 'salt-lake-city', cost: 18 },
    ],
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    region: 'southwest',
    x: 220,
    y: 330,
    connections: [
      { cityId: 'los-angeles', cost: 11 },
      { cityId: 'san-diego', cost: 14 },
      { cityId: 'santa-fe', cost: 18 },
    ],
  },

  // Central Region
  {
    id: 'salt-lake-city',
    name: 'Salt Lake City',
    region: 'central',
    x: 240,
    y: 180,
    connections: [
      { cityId: 'boise', cost: 8 },
      { cityId: 'las-vegas', cost: 18 },
      { cityId: 'denver', cost: 21 },
    ],
  },
  {
    id: 'denver',
    name: 'Denver',
    region: 'central',
    x: 340,
    y: 220,
    connections: [
      { cityId: 'salt-lake-city', cost: 21 },
      { cityId: 'santa-fe', cost: 13 },
      { cityId: 'kansas-city', cost: 16 },
      { cityId: 'omaha', cost: 14 },
    ],
  },
  {
    id: 'santa-fe',
    name: 'Santa Fe',
    region: 'central',
    x: 320,
    y: 300,
    connections: [
      { cityId: 'phoenix', cost: 18 },
      { cityId: 'denver', cost: 13 },
      { cityId: 'kansas-city', cost: 16 },
      { cityId: 'dallas', cost: 16 },
    ],
  },

  // South Region
  {
    id: 'dallas',
    name: 'Dallas',
    region: 'south',
    x: 450,
    y: 350,
    connections: [
      { cityId: 'santa-fe', cost: 16 },
      { cityId: 'kansas-city', cost: 12 },
      { cityId: 'memphis', cost: 12 },
      { cityId: 'houston', cost: 5 },
    ],
  },
  {
    id: 'houston',
    name: 'Houston',
    region: 'south',
    x: 480,
    y: 410,
    connections: [
      { cityId: 'dallas', cost: 5 },
      { cityId: 'new-orleans', cost: 8 },
    ],
  },
  {
    id: 'new-orleans',
    name: 'New Orleans',
    region: 'south',
    x: 570,
    y: 420,
    connections: [
      { cityId: 'houston', cost: 8 },
      { cityId: 'memphis', cost: 7 },
      { cityId: 'birmingham', cost: 11 },
    ],
  },

  // Midwest Region
  {
    id: 'omaha',
    name: 'Omaha',
    region: 'midwest',
    x: 440,
    y: 180,
    connections: [
      { cityId: 'denver', cost: 14 },
      { cityId: 'kansas-city', cost: 5 },
      { cityId: 'chicago', cost: 13 },
    ],
  },
  {
    id: 'kansas-city',
    name: 'Kansas City',
    region: 'midwest',
    x: 470,
    y: 240,
    connections: [
      { cityId: 'denver', cost: 16 },
      { cityId: 'santa-fe', cost: 16 },
      { cityId: 'omaha', cost: 5 },
      { cityId: 'chicago', cost: 8 },
      { cityId: 'dallas', cost: 12 },
      { cityId: 'memphis', cost: 12 },
    ],
  },
  {
    id: 'chicago',
    name: 'Chicago',
    region: 'midwest',
    x: 580,
    y: 180,
    connections: [
      { cityId: 'omaha', cost: 13 },
      { cityId: 'kansas-city', cost: 8 },
      { cityId: 'memphis', cost: 7 },
      { cityId: 'cincinnati', cost: 7 },
      { cityId: 'detroit', cost: 7 },
    ],
  },
  {
    id: 'memphis',
    name: 'Memphis',
    region: 'midwest',
    x: 560,
    y: 310,
    connections: [
      { cityId: 'dallas', cost: 12 },
      { cityId: 'kansas-city', cost: 12 },
      { cityId: 'chicago', cost: 7 },
      { cityId: 'cincinnati', cost: 12 },
      { cityId: 'birmingham', cost: 6 },
      { cityId: 'new-orleans', cost: 7 },
    ],
  },

  // Southeast Region
  {
    id: 'birmingham',
    name: 'Birmingham',
    region: 'southeast',
    x: 630,
    y: 350,
    connections: [
      { cityId: 'memphis', cost: 6 },
      { cityId: 'new-orleans', cost: 11 },
      { cityId: 'atlanta', cost: 3 },
    ],
  },
  {
    id: 'atlanta',
    name: 'Atlanta',
    region: 'southeast',
    x: 680,
    y: 340,
    connections: [
      { cityId: 'birmingham', cost: 3 },
      { cityId: 'cincinnati', cost: 15 },
      { cityId: 'raleigh', cost: 7 },
      { cityId: 'savannah', cost: 7 },
    ],
  },
  {
    id: 'savannah',
    name: 'Savannah',
    region: 'southeast',
    x: 740,
    y: 360,
    connections: [
      { cityId: 'atlanta', cost: 7 },
      { cityId: 'raleigh', cost: 7 },
      { cityId: 'jacksonville', cost: 0 },
    ],
  },
  {
    id: 'jacksonville',
    name: 'Jacksonville',
    region: 'southeast',
    x: 760,
    y: 410,
    connections: [
      { cityId: 'savannah', cost: 0 },
      { cityId: 'tampa', cost: 4 },
    ],
  },
  {
    id: 'tampa',
    name: 'Tampa',
    region: 'southeast',
    x: 750,
    y: 460,
    connections: [
      { cityId: 'jacksonville', cost: 4 },
      { cityId: 'miami', cost: 4 },
    ],
  },
  {
    id: 'miami',
    name: 'Miami',
    region: 'southeast',
    x: 760,
    y: 520,
    connections: [{ cityId: 'tampa', cost: 4 }],
  },

  // Northeast Region
  {
    id: 'detroit',
    name: 'Detroit',
    region: 'northeast',
    x: 650,
    y: 150,
    connections: [
      { cityId: 'chicago', cost: 7 },
      { cityId: 'cincinnati', cost: 4 },
      { cityId: 'pittsburgh', cost: 6 },
    ],
  },
  {
    id: 'cincinnati',
    name: 'Cincinnati',
    region: 'northeast',
    x: 670,
    y: 230,
    connections: [
      { cityId: 'chicago', cost: 7 },
      { cityId: 'memphis', cost: 12 },
      { cityId: 'detroit', cost: 4 },
      { cityId: 'pittsburgh', cost: 7 },
      { cityId: 'knoxville', cost: 6 },
      { cityId: 'atlanta', cost: 15 },
    ],
  },
  {
    id: 'knoxville',
    name: 'Knoxville',
    region: 'northeast',
    x: 710,
    y: 280,
    connections: [
      { cityId: 'cincinnati', cost: 6 },
      { cityId: 'raleigh', cost: 3 },
      { cityId: 'atlanta', cost: 5 },
    ],
  },
  {
    id: 'pittsburgh',
    name: 'Pittsburgh',
    region: 'northeast',
    x: 740,
    y: 190,
    connections: [
      { cityId: 'detroit', cost: 6 },
      { cityId: 'cincinnati', cost: 7 },
      { cityId: 'knoxville', cost: 5 },
      { cityId: 'raleigh', cost: 3 },
      { cityId: 'washington', cost: 6 },
    ],
  },
  {
    id: 'raleigh',
    name: 'Raleigh',
    region: 'northeast',
    x: 790,
    y: 270,
    connections: [
      { cityId: 'knoxville', cost: 3 },
      { cityId: 'pittsburgh', cost: 3 },
      { cityId: 'atlanta', cost: 7 },
      { cityId: 'savannah', cost: 7 },
      { cityId: 'washington', cost: 1 },
    ],
  },
  {
    id: 'washington',
    name: 'Washington',
    region: 'northeast',
    x: 820,
    y: 230,
    connections: [
      { cityId: 'pittsburgh', cost: 6 },
      { cityId: 'raleigh', cost: 1 },
      { cityId: 'philadelphia', cost: 3 },
    ],
  },
  {
    id: 'philadelphia',
    name: 'Philadelphia',
    region: 'northeast',
    x: 860,
    y: 210,
    connections: [
      { cityId: 'washington', cost: 3 },
      { cityId: 'new-york', cost: 0 },
    ],
  },
  {
    id: 'new-york',
    name: 'New York',
    region: 'northeast',
    x: 880,
    y: 180,
    connections: [
      { cityId: 'philadelphia', cost: 0 },
      { cityId: 'boston', cost: 3 },
    ],
  },
  {
    id: 'boston',
    name: 'Boston',
    region: 'northeast',
    x: 910,
    y: 140,
    connections: [{ cityId: 'new-york', cost: 3 }],
  },
];
